<a href="https://colab.research.google.com/github/Kaini9/Netflix_Dataset_Pandas_125_Questions/blob/main/netflix_125_question_workbook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas Practice Workbook — Netflix Dataset (125 Questions)
**Prepared by Ananda Rimal** · Dataset: `netflix_titles.csv`

**Columns:** `show_id, type, title, director, cast, country, date_added, release_year, rating, duration, listed_in, description`

**Instructions**
- Write your answer in the code cell **below each question**
- Every answer must be pandas code — no manual counting
- Sections G (GroupBy) and H (Cleaning) may need columns you create along the way — read carefully

| Section | Topic | Questions |
|---------|-------|-----------|
| A | First Analysis of Data | 15 |
| B | Selection with `[]`, `.loc`, `.iloc` | 25 |
| C | Conditions (with `.loc`) | 20 |
| D | Sorting | 10 |
| E | Updating Data | 15 |
| F | GroupBy | 20 |
| G | Cleaning | 20 |
| **Total** | | **125** |

## Section A — First Analysis of Data (Q1–Q15)

#### Q1. Load the dataset into a DataFrame called `df` and display the first 5 rows.

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("/content/NetFlix.csv")

#### Q2. Display the **last 7 rows** of the DataFrame.

In [3]:
# Your answer here
df.tail(7)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,description
7780,s993,TV Show,Bloodride,NaN,"Ine Marie Wilmann, Bjørnar Teigen, Emma Spetal...",Norway,13-Mar-20,2020,TV-MA,1,"International TV Shows, TV Horror, TV Mysteries",The doomed passengers aboard a spectral bus he...
7781,s994,Movie,Blow,Ted Demme,"Johnny Depp, Penélope Cruz, Franka Potente, Ra...",United States,1-Oct-19,2001,R,123,Dramas,Cocaine smuggler George rises from poverty to ...
7782,s995,TV Show,Blown Away,NaN,NaN,Canada,12-Jul-19,2019,TV-14,1,"International TV Shows, Reality TV",Ten master artists turn up the heat in glassbl...
7783,s996,TV Show,Blue Exorcist,NaN,"Nobuhiko Okamoto, Jun Fukuyama, Kana Hanazawa,...",Japan,1-Sep-20,2017,TV-MA,2,"Anime Series, International TV Shows",Determined to throw off the curse of being Sat...
7784,s997,Movie,Blue Is the Warmest Color,Abdellatif Kechiche,"Léa Seydoux, Adèle Exarchopoulos, Salim Kechio...","France, Belgium, Spain",26-Aug-16,2013,NC-17,180,"Dramas, Independent Movies, International Movies","Determined to fall in love, 15-year-old Adele ..."
7785,s998,Movie,Blue Jasmine,Woody Allen,"Cate Blanchett, Sally Hawkins, Alec Baldwin, L...",United States,8-Mar-19,2013,PG-13,98,"Comedies, Dramas, Independent Movies",The high life leads to high anxiety for a fash...
7786,s999,Movie,Blue Jay,Alex Lehmann,"Sarah Paulson, Mark Duplass, Clu Gulager",United States,6-Dec-16,2016,TV-MA,81,"Dramas, Independent Movies, Romantic Movies",Two former high school sweethearts unexpectedl...

#### Q3. How many rows and columns does the dataset have?

In [9]:
total=df.shape
print("total rows and column:", total)

total rows and column: (7787, 12)

#### Q4. Display the names of all columns.

In [14]:
# Your answer here
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'genres', 'description'],
      dtype='object')

In [15]:
df.loc[1,:]

show_id                                                       s10
type                                                        Movie
title                                                        1920
director                                             Vikram Bhatt
cast            Rajneesh Duggal, Adah Sharma, Indraneil Sengup...
country                                                     India
date_added                                              15-Dec-17
release_year                                                 2008
rating                                                      TV-MA
duration                                                      143
genres             Horror Movies, International Movies, Thrillers
description     An architect and his wife move into a castle t...
Name: 1, dtype: object

#### Q5. Use `info()` — which columns have missing values, and what is the data type of each column?

In [16]:
# Your answer here
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7787 entries, 0 to 7786
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       7787 non-null   object
 1   type          7787 non-null   object
 2   title         7787 non-null   object
 3   director      5398 non-null   object
 4   cast          7069 non-null   object
 5   country       7280 non-null   object
 6   date_added    7777 non-null   object
 7   release_year  7787 non-null   int64
 8   rating        7780 non-null   object
 9   duration      7787 non-null   int64
 10  genres        7787 non-null   object
 11  description   7787 non-null   object
dtypes: int64(2), object(10)
memory usage: 730.2+ KB

#### Q6. Use `describe()` on the numeric columns. What is the minimum and maximum `release_year`?

In [27]:
df.describe()

       release_year     duration
count   7787.000000  7787.000000
mean    2013.932580    69.122769
std        8.757395    50.950743
min     1925.000000     1.000000
25%     2013.000000     2.000000
50%     2017.000000    88.000000
75%     2018.000000   106.000000
max     2021.000000   312.000000

In [25]:
# Your answer here
print(df["release_year"].min(),df["release_year"].max())

1925 2021

#### Q7. Use `describe(include="object")` on the text columns. Which value appears most often in the `type` column?

In [28]:
# Your answer here
df.describe(include="object")

,show_id,type,title,director,cast,country,date_added,rating,genres,description
count,7787,7787,7787,5398,7069,7280,7777,7780,7787,7787
unique,7787,2,7787,4049,6831,681,1565,14,492,7769
top,s999,Movie,Blue Jay,"Raúl Campos, Jan Suter",David Attenborough,United States,1-Jan-20,TV-MA,Documentaries,Multiple women report their husbands as missin...
freq,1,5377,1,18,18,2555,118,2863,334,3

In [30]:
df["type"].value_counts()

type
Movie      5377
TV Show    2410
Name: count, dtype: int64

#### Q8. Count the missing values in **every** column with one command.

In [32]:
# Your answer here
df.isnull().sum()

show_id            0
type               0
title              0
director        2389
cast             718
country          507
date_added        10
release_year       0
rating             7
duration           0
genres             0
description        0
dtype: int64

#### Q9. Which single column has the **most** missing values?

In [36]:
# Your answer here
df.isnull().sum().idxmax()

'director'

#### Q10. How many **unique** values are in the `rating` column? Display them.

In [38]:
# Your answer here
df["rating"].nunique()

14

In [39]:
df["rating"].unique()

array(['TV-MA', 'TV-PG', 'R', 'TV-G', 'PG-13', 'TV-14', 'TV-Y', 'PG',
       'TV-Y7', 'NR', 'G', 'TV-Y7-FV', nan, 'UR', 'NC-17'], dtype=object)

#### Q11. Show 5 **random** rows using `sample()`.

In [40]:
# Your answer here
df.sample(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,description
3784,s4404,TV Show,Narcoworld: Dope Stories,NaN,NaN,United States,22-Nov-19,2019,TV-MA,1,"Crime TV Shows, Docuseries",Ride along as police officers and drug smuggle...
542,s1487,Movie,Consequences,Ozan Açıktan,"Nehir Erdoğan, Tardu Flordun, İlker Kaleli, Se...",Turkey,25-Oct-19,2014,TV-MA,106,"Dramas, International Movies, Thrillers",Secrets bubble to the surface after a sensual ...
2689,s3419,TV Show,Kitten Rescuers,NaN,Jo Brand,United Kingdom,2-Oct-19,2017,TV-14,1,"British TV Shows, International TV Shows, Real...",Cat-crazy host Jo Brand follows vets and anima...
4036,s4631,TV Show,Once Upon a Time,NaN,"Ruby, Mohamed Farraag, Ahmed Dawood, Sawsan Ba...",Egypt,9-Dec-20,2019,TV-14,1,"International TV Shows, Romantic TV Shows, TV ...",Fighting to save his ancestors' mansion from d...
5553,s5998,Movie,Taylor Tomlinson: Quarter-Life Crisis,Marcus Raboy,Taylor Tomlinson,United States,3-Mar-20,2020,TV-MA,61,Stand-Up Comedy,She's halfway through her 20s — and she's over...

#### Q12. What is the memory usage of the DataFrame? (hint: `info()` or `memory_usage()`)

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7787 entries, 0 to 7786
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       7787 non-null   object
 1   type          7787 non-null   object
 2   title         7787 non-null   object
 3   director      5398 non-null   object
 4   cast          7069 non-null   object
 5   country       7280 non-null   object
 6   date_added    7777 non-null   object
 7   release_year  7787 non-null   int64
 8   rating        7780 non-null   object
 9   duration      7787 non-null   int64
 10  genres        7787 non-null   object
 11  description   7787 non-null   object
dtypes: int64(2), object(10)
memory usage: 730.2+ KB

In [46]:
# Your answer here
df.memory_usage().sum()

np.int64(747684)

#### Q13. Display the data type of only the `release_year` column.

In [49]:
# Your answer here
df["release_year"].dtype

dtype('int64')

#### Q14. Count how many titles are of each `type` using `value_counts()`.

In [53]:
# Your answer here
df["type"].value_counts()

type
Movie      5377
TV Show    2410
Name: count, dtype: int64

#### Q15. Check: does the dataset contain any **fully duplicated** rows?

In [54]:
# Your answer here
df.duplicated().sum()

np.int64(0)

## Section B — Selection with `[]`, `.loc`, `.iloc` (Q16–Q40)
*(Q16–Q30: default 0,1,2,... index · Q31–Q40: after `set_index("show_id")`)*

#### Q16. Select the `title` column as a **Series**.

In [56]:
# Your answer here
df["title"]

0                                              3%
1                                            1920
2                                      3 Heroines
3       Blue Mountain State: The Rise of Thadland
4                                  Blue Planet II
                          ...
7782                                   Blown Away
7783                                Blue Exorcist
7784                    Blue Is the Warmest Color
7785                                 Blue Jasmine
7786                                     Blue Jay
Name: title, Length: 7787, dtype: object

#### Q17. Select the `title` column as a **DataFrame** (hint: double brackets).

In [57]:
# Your answer here
df[["title"]]

                                          title
0                                            3%
1                                          1920
2                                    3 Heroines
3     Blue Mountain State: The Rise of Thadland
4                                Blue Planet II
...                                         ...
7782                                 Blown Away
7783                              Blue Exorcist
7784                  Blue Is the Warmest Color
7785                               Blue Jasmine
7786                                   Blue Jay

[7787 rows x 1 columns]

#### Q18. Select the columns `title`, `type`, and `country` together.

In [58]:
# Your answer here
df[["title","type","country"]]

,title,type,country
0,3%,TV Show,Brazil
1,1920,Movie,India
2,3 Heroines,Movie,Indonesia
3,Blue Mountain State: The Rise of Thadland,Movie,United States
4,Blue Planet II,TV Show,United Kingdom
...,...,...,...
7782,Blown Away,TV Show,Canada
7783,Blue Exorcist,TV Show,Japan
7784,Blue Is the Warmest Color,Movie,"France, Belgium, Spain"
7785,Blue Jasmine,Movie,United States
7786,Blue Jay,Movie,United States

#### Q19. Select the first 10 rows using `.iloc`.

In [62]:
# Your answer here
df.iloc[:10]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,description
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,14-Aug-20,2020,TV-MA,4,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,s10,Movie,1920,Vikram Bhatt,"Rajneesh Duggal, Adah Sharma, Indraneil Sengup...",India,15-Dec-17,2008,TV-MA,143,"Horror Movies, International Movies, Thrillers",An architect and his wife move into a castle t...
2,s100,Movie,3 Heroines,Iman Brotoseno,"Reza Rahadian, Bunga Citra Lestari, Tara Basro...",Indonesia,5-Jan-19,2016,TV-PG,124,"Dramas, International Movies, Sports Movies",Three Indonesian women break records by becomi...
3,s1000,Movie,Blue Mountain State: The Rise of Thadland,Lev L. Spiro,"Alan Ritchson, Darin Brooks, James Cade, Rob R...",United States,1-Mar-16,2016,R,90,Comedies,New NFL star Thad buys his old teammates' belo...
4,s1001,TV Show,Blue Planet II,NaN,David Attenborough,United Kingdom,3-Dec-18,2017,TV-G,1,"British TV Shows, Docuseries, Science & Nature TV",This sequel to the award-winning nature series...
5,s1002,Movie,Blue Ruin,Jeremy Saulnier,"Macon Blair, Devin Ratray, Amy Hargreaves, Kev...","United States, France",25-Feb-19,2013,R,90,"Independent Movies, Thrillers",Bad news from the past unhinges vagabond Dwigh...
6,s1003,Movie,Blue Streak,Les Mayfield,"Martin Lawrence, Luke Wilson, Peter Greene, Da...","Germany, United States",1-Jan-21,1999,PG-13,94,"Action & Adventure, Comedies",A jewel thief returns to his hiding place afte...
7,s1004,Movie,Blue Valentine,Derek Cianfrance,"Ryan Gosling, Michelle Williams, Faith Wladyka...",United States,5-Jul-18,2010,R,112,"Dramas, Independent Movies, Romantic Movies",As Cindy and Dean muddle through their languis...
8,s1005,Movie,BluffMaster!,Rohan Sippy,"Abhishek Bachchan, Priyanka Chopra, Riteish De...",India,8-Jan-21,2005,TV-14,129,"Comedies, International Movies, Romantic Movies",When his girlfriend learns the truth about his...
9,s1006,Movie,Blurred Lines: Inside the Art World,Barry Avrich,NaN,Canada,31-Dec-17,2017,TV-MA,85,Documentaries,Artists and industry insiders shed light on th...

#### Q20. Select rows with labels 10 to 20 using `.loc`. How many rows do you get and why?

In [64]:
# Your answer here
df.loc[10:20]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,description
10,s1007,TV Show,BNA,NaN,"Sumire Morohoshi, Yoshimasa Hosoya, Maria Naga...",Japan,30-Jun-20,2020,TV-14,1,"Anime Series, International TV Shows","Morphed into a raccoon beastman, Michiru seeks..."
11,s1008,Movie,BNK48: Girls Don't Cry,Nawapol Thamrongrattanarit,NaN,Thailand,1-Mar-19,2018,TV-14,108,"Documentaries, International Movies, Music & M...",Members of the Thai idol girl group BNK48 open...
12,s1009,Movie,Bo Burnham: Make Happy,"Bo Burnham, Christopher Storer",Bo Burnham,United States,3-Jun-16,2016,TV-MA,60,"Music & Musicals, Stand-Up Comedy",Combining his trademark wit and self-deprecati...
13,s101,Movie,3 Idiots,Rajkumar Hirani,"Aamir Khan, Kareena Kapoor, Madhavan, Sharman ...",India,1-Aug-19,2009,PG-13,164,"Comedies, Dramas, International Movies",While attending one of India's premier college...
14,s1010,Movie,Bo Burnham: what.,"Bo Burnham, Christopher Storer",Bo Burnham,United States,1-Jul-18,2013,TV-MA,60,Stand-Up Comedy,Left brain and right brain duke it out – and u...
15,s1011,TV Show,Bo on the Go!,NaN,"Catherine O'Connor, Andrew Sabiston, Jim Fowler",Canada,21-Mar-19,2007,TV-Y,1,Kids' TV,Staying at home doesn't mean sitting still for...
16,s1012,Movie,Bob Lazar: Area 51 & Flying Saucers,Jeremy Kenyon Lockyer Corbell,Robert Lazar,United States,18-Jun-19,2018,TV-MA,97,Documentaries,"Decades ago, Bob Lazar blew the whistle on Are..."
17,s1013,TV Show,Bob Ross: Beauty Is Everywhere,NaN,Bob Ross,NaN,1-Jun-16,1991,TV-G,1,TV Shows,"""The Joy of Painting"" host Bob Ross brings his..."
18,s1014,Movie,Bob's Broken Sleigh,Jay Surridge,"Cole Howard, Bruce Greenwood, Victor Garber, M...",Canada,17-Dec-15,2015,TV-G,47,Children & Family Movies,"An overly eager elf improves Santa's sleigh, b..."
19,s1015,Movie,Bobbi Jene,Elvira Lind,Bobbi Jene Smith,"Denmark, Sweden, Israel, United States",1-Jun-18,2017,TV-MA,99,Documentaries,This candid profile follows dancer Bobbi Jene ...
20,s1016,Movie,Bobbleheads The Movie,Kirk Wise,"Jennifer Coolidge, Karen Fukuhara, Khary Payto...",United States,8-Dec-20,2020,PG,83,"Children & Family Movies, Comedies",A team of bobbleheads band together to defend ...

#### Q21. Using `.iloc`, select rows at positions 5 to 14 (10 rows). Compare with Q20 — why is the row count logic different?

In [ ]:
# Your answer here

#### Q22. Using `.loc`, select rows 0 to 9 with only the columns `title` and `release_year`.

In [ ]:
# Your answer here

#### Q23. Using `.iloc`, select the first 8 rows and the first 5 columns.

In [ ]:
# Your answer here

#### Q24. Using `.iloc`, select the **last row** of the DataFrame.

In [ ]:
# Your answer here

#### Q25. Using `.iloc`, select the last 5 rows and the last 2 columns (negative positions).

In [ ]:
# Your answer here

#### Q26. Using `.loc`, get the value of `title` for the row with label 50.

In [ ]:
# Your answer here

#### Q27. Using `.iloc`, get the value in row position 100, column position 2. Which column is that?

In [ ]:
# Your answer here

#### Q28. Using `.iloc`, select every 100th row (hint: slicing with a step `::100`).

In [ ]:
# Your answer here

#### Q29. Using `.loc`, select rows 0 to 4 and **all** columns from `title` to `country` (label slicing on columns!).

In [ ]:
# Your answer here

#### Q30. Select three specific rows by label — 3, 33, and 333 — in one `.loc` call.

In [ ]:
# Your answer here

#### Q31. Set `show_id` as the index of `df` (keep it for the rest of Section B). Display the head.

In [ ]:
# Your answer here

#### Q32. Using `.loc`, select the row with label `"s1"`.

In [ ]:
# Your answer here

#### Q33. Using `.loc`, select rows `"s10"` to `"s15"`. Does label slicing still include the end?

In [ ]:
# Your answer here

#### Q34. Using `.iloc`, select the row at position 0. Is it the same row as label `"s1"`?

In [ ]:
# Your answer here

#### Q35. Using `.loc`, get the `title` and `type` of the show with id `"s500"`.

In [ ]:
# Your answer here

#### Q36. Using `.iloc`, select the row at position 499. Is its label `"s500"`? Explain why or why not in a comment.

In [ ]:
# Your answer here

#### Q37. Using `.loc`, select shows `"s1"`, `"s100"`, and `"s1000"` with columns `title` and `release_year`.

In [ ]:
# Your answer here

#### Q38. What happens if you run `df.loc[0]` now? Try it, read the error, and explain in a comment.

In [ ]:
# Your answer here

#### Q39. Using `.iloc`, select rows at positions [0, 99, 999] in one call.

In [ ]:
# Your answer here

#### Q40. Reset the index back to 0,1,2,... using `reset_index()`. Display the head.

In [ ]:
# Your answer here

## Section C — Conditions with `.loc` (Q41–Q60)
*Write every filter with `df.loc[condition]` or `df.loc[condition, columns]` style where possible.*

#### Q41. Select all rows where `type` is `"Movie"`.

In [ ]:
# Your answer here

#### Q42. Select all rows where `type` is `"TV Show"` — show only `title` and `country` using one `.loc` call.

In [ ]:
# Your answer here

#### Q43. Select all titles released in 2021.

In [ ]:
# Your answer here

#### Q44. Select all titles released **before** 2000.

In [ ]:
# Your answer here

#### Q45. Select all titles released between 2015 and 2020 (inclusive) — two conditions with `&`.

In [ ]:
# Your answer here

#### Q46. Select all Movies released after 2019 (two conditions).

In [ ]:
# Your answer here

#### Q47. Select all titles where `rating` is `"TV-MA"`.

In [ ]:
# Your answer here

#### Q48. Select all titles where `rating` is either `"PG"` or `"PG-13"` using `.isin()`.

In [ ]:
# Your answer here

#### Q49. Select all titles where `rating` is **NOT** `"TV-MA"` (hint: `~` or `!=`).

In [ ]:
# Your answer here

#### Q50. Select all titles where `country` is exactly `"India"`.

In [ ]:
# Your answer here

#### Q51. Select all titles where `country` **contains** `"India"` (hint: `str.contains`, use `na=False`). Why is the row count different from the previous question?

In [ ]:
# Your answer here

#### Q52. Select all Movies from the United States — show only `title` and `release_year`.

In [ ]:
# Your answer here

#### Q53. Select all titles where `director` is missing (hint: `isna()`).

In [ ]:
# Your answer here

#### Q54. Select all titles where `director` is **not** missing.

In [ ]:
# Your answer here

#### Q55. Select all TV Shows released in 2020 **or** 2021.

In [ ]:
# Your answer here

#### Q56. Select all titles whose `title` starts with the letter `"A"` (hint: `str.startswith`, `na=False`).

In [ ]:
# Your answer here

#### Q57. Select all titles whose `title` contains the word `"Love"`.

In [ ]:
# Your answer here

#### Q58. Using `.loc` with a condition, show the `title`, `rating`, and `release_year` of all Movies rated `"R"`.

In [ ]:
# Your answer here

#### Q59. Count how many Movies were released after 2015 (condition + `len()` or `.shape`).

In [ ]:
# Your answer here

#### Q60. Challenge: select all Movies that are from India **or** Nepal and released after 2010 — careful with brackets around the `|` condition!

In [ ]:
# Your answer here

## Section D — Sorting (Q61–Q70)

#### Q61. Sort the DataFrame by `release_year` ascending. Show the head — what are the oldest titles?

In [ ]:
# Your answer here

#### Q62. Sort by `release_year` **descending**. Show the 10 newest titles.

In [ ]:
# Your answer here

#### Q63. Sort by `title` alphabetically.

In [ ]:
# Your answer here

#### Q64. Sort by `release_year` descending AND `title` ascending at the same time (list of columns + list of ascending values).

In [ ]:
# Your answer here

#### Q65. Sort by `rating`, and show only `title` and `rating` in the result.

In [ ]:
# Your answer here

#### Q66. Sort the **index** using `sort_index()` (useful after filtering).

In [ ]:
# Your answer here

#### Q67. Show the 5 oldest Movies (filter first, then sort, then head).

In [ ]:
# Your answer here

#### Q68. Show the 5 newest TV Shows.

In [ ]:
# Your answer here

#### Q69. Sort by `country` and put the missing values **first** (hint: `na_position="first"`).

In [ ]:
# Your answer here

#### Q70. What does `ascending=[False, True]` mean when sorting by two columns? Demonstrate with `release_year` and `title` and explain in a comment.

In [ ]:
# Your answer here

## Section E — Updating Data (Q71–Q85)

#### Q71. Rename the column `listed_in` to `genres` (keep this change).

In [ ]:
# Your answer here

#### Q72. Create a new column `age_years` = 2026 minus `release_year`.

In [ ]:
# Your answer here

#### Q73. Create a column `is_movie` that is `True` when `type` is `"Movie"`.

In [ ]:
# Your answer here

#### Q74. Create a column `is_recent` that is `True` when `release_year >= 2020`.

In [ ]:
# Your answer here

#### Q75. Using `.loc` with a condition, set `rating` to `"UNRATED"` for all rows where `rating` is missing.

In [ ]:
# Your answer here

#### Q76. Replace the value `"United States"` with `"USA"` in the `country` column (hint: `replace`).

In [ ]:
# Your answer here

#### Q77. Convert all titles to UPPERCASE into a new column `title_upper` (hint: `str.upper`).

In [ ]:
# Your answer here

#### Q78. Create a column `title_length` = number of characters in each title (hint: `str.len`).

In [ ]:
# Your answer here

#### Q79. Using `.loc`, change the `title` of the row with index label 0 to `"My Favourite Show"`. Display that row to confirm.

In [ ]:
# Your answer here

#### Q80. Add a column `platform` where every row has the value `"Netflix"`.

In [ ]:
# Your answer here

#### Q81. Delete the column `title_upper` using `drop`.

In [ ]:
# Your answer here

#### Q82. Change `release_year` to type `int32` using `astype`. Check with `dtypes`.

In [ ]:
# Your answer here

#### Q83. Using `.loc` with a condition, create/overwrite a column `era` = `"old"` for titles before 2010 and `"new"` for 2010 onward (two `.loc` assignments, or `np.where`).

In [ ]:
# Your answer here

#### Q84. Increase `age_years` by 1 for **all** rows in one operation.

In [ ]:
# Your answer here

#### Q85. Explain in a markdown comment: why is `df.loc[condition, "col"] = value` the SAFE way to update, instead of `df[condition]["col"] = value`? (SettingWithCopyWarning!)

In [ ]:
# Your answer here

## Section F — GroupBy (Q86–Q105)

#### Q86. Group by `type` and count the number of titles in each group (`size()`).

In [ ]:
# Your answer here

#### Q87. Group by `rating` and count titles. Which rating is most common?

In [ ]:
# Your answer here

#### Q88. Group by `release_year` and count titles. Which year had the most releases?

In [ ]:
# Your answer here

#### Q89. Group by `type` and find the **minimum** and **maximum** `release_year` for each (hint: `agg(["min","max"])`).

In [ ]:
# Your answer here

#### Q90. Group by `type` and compute the **average** `age_years`.

In [ ]:
# Your answer here

#### Q91. Group by `country` and count titles — show only the top 10 (sort + head).

In [ ]:
# Your answer here

#### Q92. Group by `rating` and compute the average `title_length`.

In [ ]:
# Your answer here

#### Q93. Group by `era` (from Q83) and count Movies vs TV Shows (hint: group by TWO columns).

In [ ]:
# Your answer here

#### Q94. Group by `type` and `rating` together and count. Display the result with `unstack()`.

In [ ]:
# Your answer here

#### Q95. For Movies only: group by `release_year` and count — how many movies came out each year since 2015? (filter first, then group, then `.tail()`)

In [ ]:
# Your answer here

#### Q96. Group by `country` and compute the average `release_year` — which 5 countries have the 'newest' catalogs on average? (sort descending, head)

In [ ]:
# Your answer here

#### Q97. Use `value_counts()` on `genres` — why does this NOT give clean genre counts? Explain in a comment (hint: multiple genres in one cell).

In [ ]:
# Your answer here

#### Q98. Group by `is_recent` and count — how many recent vs old titles?

In [ ]:
# Your answer here

#### Q99. Group by `type` and use `.agg()` with a dictionary: count of `title` and mean of `age_years` in ONE command.

In [ ]:
# Your answer here

#### Q100. Group by `rating` and show the **number of unique countries** per rating (hint: `nunique`).

In [ ]:
# Your answer here

#### Q101. Using `groupby` + `head(1)`, show the FIRST title (by current order) in each `type` group.

In [ ]:
# Your answer here

#### Q102. Group by `release_year` and count, then plot it with `.plot()` (line chart). What trend do you see?

In [ ]:
# Your answer here

#### Q103. Group by `year_added`-style logic isn't possible yet — `date_added` is still text! Group by the **first 4 characters trick is wrong**. Explain in a comment why we need Section G (Cleaning) before we can group by the year a title was ADDED.

In [ ]:
# Your answer here

#### Q104. Group by `type` and compute the **median** `release_year`.

In [ ]:
# Your answer here

#### Q105. Challenge: for each `rating`, what percentage of titles are Movies? (hint: group by rating, compute the mean of `is_movie`, multiply by 100)

In [ ]:
# Your answer here

## Section G — Cleaning (Q106–Q125)

#### Q106. Re-check missing values per column (things changed since Section A!).

In [ ]:
# Your answer here

#### Q107. Fill missing `director` values with `"Unknown"`.

In [ ]:
# Your answer here

#### Q108. Fill missing `cast` values with `"Unknown"`.

In [ ]:
# Your answer here

#### Q109. Fill missing `country` values with the **most common** country (hint: `mode()[0]`).

In [ ]:
# Your answer here

#### Q110. Count the rows where `date_added` is missing, then drop those rows.

In [ ]:
# Your answer here

#### Q111. `date_added` has extra spaces in some rows — strip them (hint: `str.strip`).

In [ ]:
# Your answer here

#### Q112. Convert `date_added` to datetime with `pd.to_datetime`. Check the dtype after.

In [ ]:
# Your answer here

#### Q113. NOW create `year_added` = `.dt.year` and `month_added` = `.dt.month_name()`.

In [ ]:
# Your answer here

#### Q114. Group by `year_added` and count — which year did Netflix add the most content? (This is the question F103 could not answer!)

In [ ]:
# Your answer here

#### Q115. Group by `month_added` and count — which month is most popular for adding content?

In [ ]:
# Your answer here

#### Q116. Look at the `duration` column with `unique()` (first 20 values) — what TWO different formats do you see?

In [ ]:
# Your answer here

#### Q117. Extract the number from `duration` into a new column `duration_int` (hint: `str.extract(r"(\\d+)")` then `astype(float)`).

In [ ]:
# Your answer here

#### Q118. For Movies only: what is the average, minimum, and maximum duration in minutes?

In [ ]:
# Your answer here

#### Q119. For TV Shows only: how many have more than 5 seasons? Show their titles.

In [ ]:
# Your answer here

#### Q120. Check duplicated **titles** (not full rows): are there any titles that appear more than once? Display them.

In [ ]:
# Your answer here

#### Q121. Are those duplicated titles real duplicates or different shows? Inspect a few with `.loc` and explain in a comment.

In [ ]:
# Your answer here

#### Q122. The `rating` column contains some WRONG values that are actually durations (like `"74 min"`) — find them (hint: `str.contains("min", na=False)`).

In [ ]:
# Your answer here

#### Q123. Fix those wrong rating rows: set their `rating` to `"UNRATED"` using `.loc`.

In [ ]:
# Your answer here

#### Q124. Final check: run `info()` and `isna().sum()` — is the dataset clean now? Summarize what you fixed in a comment.

In [ ]:
# Your answer here

#### Q125. Save your cleaned DataFrame to a new file `netflix_clean.csv` (without the index). This file is your submission proof!

In [ ]:
# Your answer here

---
## Submission
- Answer **all 125 questions** — partial answers get partial marks
- Run All must work top to bottom without errors (−5 marks if it crashes)
- Submit BOTH files: `YourName_workbook.ipynb` and `netflix_clean.csv`